export const laptops = [
  {
    image: "https://source.unsplash.com/featured/500x500?laptop-product",
    isOnFlashSale: false,
    brand: "Dell",
    model: "XPS 13",
    release_year: 2021,
    processor: "Intel Core i7-1165G7",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "13.4 inches",
    resolution: "3840 x 2400",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.8 lbs",
    price: 1299.99,
    colors: ["Platinum Silver", "Frost White"],
    description:
      "The Dell XPS 13 is a premium ultrabook with a stunning 4K display and powerful performance.",
    ratings: {
      average: 4.5,
      count: 100,
    },
    reviews: [
      {
        username: "JohnDoe",
        rating: 5,
        comment: "Excellent laptop!",
      },
      {
        username: "AliceSmith",
        rating: 4,
        comment: "Great build quality.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/501x501?laptop-product",
    isOnFlashSale: false,
    brand: "HP",
    model: "HP Spectre x360",
    release_year: 2021,
    processor: "Intel Core i7-1165G7",
    ram: "16GB",
    storage: "1TB SSD",
    display_size: "13.3 inches",
    resolution: "1920 x 1080",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.87 lbs",
    price: 1399.99,
    colors: ["Nightfall Black", "Poseidon Blue"],
    description:
      "The HP Spectre x360 is a versatile 2-in-1 laptop with a sleek design and long battery life.",
    ratings: {
      average: 4.6,
      count: 90,
    },
    reviews: [
      {
        username: "EmilyJohnson",
        rating: 5,
        comment: "Amazing laptop!",
      },
      {
        username: "DavidWilson",
        rating: 4,
        comment: "Impressive performance.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/502x502?laptop-product",
    isOnFlashSale: false,
    brand: "Apple",
    model: "MacBook Air",
    release_year: 2020,
    processor: "Apple M1",
    ram: "8GB",
    storage: "256GB SSD",
    display_size: "13.3 inches",
    resolution: "2560 x 1600",
    graphics_card: "Apple GPU",
    weight: "2.8 lbs",
    price: 999.99,
    colors: ["Space Gray", "Silver"],
    description:
      "The MacBook Air with Apple's M1 chip offers impressive performance and battery life.",
    ratings: {
      average: 4.7,
      count: 120,
    },
    reviews: [
      {
        username: "SophiaBrown",
        rating: 5,
        comment: "A fantastic laptop!",
      },
      {
        username: "MichaelJones",
        rating: 5,
        comment: "Incredible battery life.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/503x503?laptop-product",
    isOnFlashSale: false,
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    release_year: 2021,
    processor: "Intel Core i7-1165G7",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "14.0 inches",
    resolution: "1920 x 1080",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.49 lbs",
    price: 1499.99,
    colors: ["Black"],
    description:
      "The Lenovo ThinkPad X1 Carbon is a premium business laptop known for its durability and performance.",
    ratings: {
      average: 4.8,
      count: 110,
    },
    reviews: [
      {
        username: "OliviaSmith",
        rating: 4,
        comment: "Excellent for work!",
      },
      {
        username: "WilliamDavis",
        rating: 5,
        comment: "Lightweight and powerful.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/504x504?laptop-product",
    isOnFlashSale: false,
    brand: "Acer",
    model: "Acer Predator Helios 300",
    release_year: 2021,
    processor: "Intel Core i7-11800H",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "15.6 inches",
    resolution: "1920 x 1080",
    graphics_card: "NVIDIA GeForce RTX 3060",
    weight: "5.51 lbs",
    price: 1299.99,
    colors: ["Abyssal Black"],
    description:
      "The Acer Predator Helios 300 is a gaming laptop with powerful hardware and a high-refresh-rate display.",
    ratings: {
      average: 4.6,
      count: 95,
    },
    reviews: [
      {
        username: "EthanWilliams",
        rating: 5,
        comment: "Great for gaming!",
      },
      {
        username: "AvaTaylor",
        rating: 4,
        comment: "Good value for the specs.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/505x505?laptop-product",
    isOnFlashSale: false,
    brand: "Microsoft",
    model: "Surface Laptop 4",
    release_year: 2021,
    processor: "Intel Core i5-1135G7",
    ram: "8GB",
    storage: "256GB SSD",
    display_size: "13.5 inches",
    resolution: "2256 x 1504",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.79 lbs",
    price: 1099.99,
    colors: ["Platinum", "Ice Blue", "Sandstone"],
    description:
      "The Microsoft Surface Laptop 4 offers a premium design and smooth performance.",
    ratings: {
      average: 4.7,
      count: 85,
    },
    reviews: [
      {
        username: "LiamJohnson",
        rating: 5,
        comment: "Sleek and powerful.",
      },
      {
        username: "OliviaBrown",
        rating: 4,
        comment: "Excellent build quality.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/506x506?laptop-product",
    isOnFlashSale: false,
    brand: "ASUS",
    model: "ASUS ROG Zephyrus G14",
    release_year: 2021,
    processor: "AMD Ryzen 9 5900HS",
    ram: "32GB",
    storage: "1TB SSD",
    display_size: "14 inches",
    resolution: "2560 x 1440",
    graphics_card: "NVIDIA GeForce RTX 3060",
    weight: "3.75 lbs",
    price: 1499.99,
    colors: ["Moonlight White", "Eclipse Gray"],
    description:
      "The ASUS ROG Zephyrus G14 is a powerful gaming laptop with a compact form factor and excellent performance.",
    ratings: {
      average: 4.8,
      count: 110,
    },
    reviews: [
      {
        username: "SophiaMiller",
        rating: 5,
        comment: "Impressive gaming performance.",
      },
      {
        username: "JamesWilson",
        rating: 4,
        comment: "Great portability for a gaming laptop.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/507x507?laptop-product",
    isOnFlashSale: false,
    brand: "Lenovo",
    model: "Lenovo Yoga C940",
    release_year: 2020,
    processor: "Intel Core i7-1065G7",
    ram: "12GB",
    storage: "512GB SSD",
    display_size: "14 inches",
    resolution: "3840 x 2160",
    graphics_card: "Intel Iris Plus Graphics",
    weight: "2.98 lbs",
    price: 1199.99,
    colors: ["Iron Gray", "Mica"],
    description:
      "The Lenovo Yoga C940 is a premium 2-in-1 laptop with a 4K touchscreen and versatile design.",
    ratings: {
      average: 4.7,
      count: 95,
    },
    reviews: [
      {
        username: "LiamSmith",
        rating: 5,
        comment: "Excellent for productivity.",
      },
      {
        username: "OliviaDavis",
        rating: 4,
        comment: "Beautiful 4K display.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/508x508?laptop-product",
    isOnFlashSale: false,
    brand: "HP",
    model: "HP Envy x360",
    release_year: 2021,
    processor: "AMD Ryzen 7 5700U",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "13.3 inches",
    resolution: "1920 x 1080",
    graphics_card: "AMD Radeon Graphics",
    weight: "2.87 lbs",
    price: 1199.99,
    colors: ["Natural Silver"],
    description:
      "The HP Envy x360 is a versatile 2-in-1 laptop with powerful AMD Ryzen performance and a sleek design.",
    ratings: {
      average: 4.6,
      count: 85,
    },
    reviews: [
      {
        username: "EmmaJohnson",
        rating: 5,
        comment: "Impressive build quality.",
      },
      {
        username: "NoahWilson",
        rating: 4,
        comment: "Great for both work and entertainment.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/509x509?laptop-product",
    isOnFlashSale: false,
    brand: "Acer",
    model: "Acer Swift 3",
    release_year: 2021,
    processor: "Intel Core i5-1135G7",
    ram: "8GB",
    storage: "256GB SSD",
    display_size: "14 inches",
    resolution: "1920 x 1080",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.65 lbs",
    price: 799.99,
    colors: ["Silver"],
    description:
      "The Acer Swift 3 is a lightweight and affordable laptop for everyday use.",
    ratings: {
      average: 4.5,
      count: 70,
    },
    reviews: [
      {
        username: "SophiaDavis",
        rating: 4,
        comment: "Good value for the price.",
      },
      {
        username: "WilliamSmith",
        rating: 4,
        comment: "Portable and reliable.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5010x5010?laptop-product",
    isOnFlashSale: false,
    brand: "Microsoft",
    model: "Surface Pro 7",
    release_year: 2019,
    processor: "Intel Core i5-1035G4",
    ram: "8GB",
    storage: "128GB SSD",
    display_size: "12.3 inches",
    resolution: "2736 x 1824",
    graphics_card: "Intel Iris Plus Graphics",
    weight: "1.7 lbs",
    price: 899.99,
    colors: ["Platinum", "Black"],
    description:
      "The Microsoft Surface Pro 7 is a versatile 2-in-1 laptop with a detachable keyboard and stylus support.",
    ratings: {
      average: 4.4,
      count: 60,
    },
    reviews: [
      {
        username: "EmmaWilson",
        rating: 5,
        comment: "Perfect for on-the-go productivity.",
      },
      {
        username: "JamesSmith",
        rating: 4,
        comment: "Excellent build quality.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5011x5011?laptop-product",
    isOnFlashSale: false,
    brand: "LG",
    model: "LG Gram 17",
    release_year: 2021,
    processor: "Intel Core i7-1165G7",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "17 inches",
    resolution: "2560 x 1600",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.98 lbs",
    price: 1499.99,
    colors: ["Dark Silver"],
    description:
      "The LG Gram 17 is an ultralight laptop with a large 17-inch display, making it ideal for productivity.",
    ratings: {
      average: 4.7,
      count: 75,
    },
    reviews: [
      {
        username: "LiamMiller",
        rating: 5,
        comment: "Amazingly lightweight for its size.",
      },
      {
        username: "OliviaJones",
        rating: 4,
        comment: "Great for multitasking.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5012x5012?laptop-product",
    isOnFlashSale: false,
    brand: "Apple",
    model: "MacBook Pro 16-inch",
    release_year: 2019,
    processor: "Intel Core i9",
    ram: "16GB",
    storage: "1TB SSD",
    display_size: "16 inches",
    resolution: "3072 x 1920",
    graphics_card: "AMD Radeon Pro 5500M",
    weight: "4.3 lbs",
    price: 2399.99,
    colors: ["Space Gray", "Silver"],
    description:
      "The MacBook Pro 16-inch offers powerful performance and a stunning Retina display.",
    ratings: {
      average: 4.8,
      count: 90,
    },
    reviews: [
      {
        username: "EthanDavis",
        rating: 5,
        comment: "Best laptop I've ever owned.",
      },
      {
        username: "AvaWilson",
        rating: 5,
        comment: "Great for creative work.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5013x5013?laptop-product",
    isOnFlashSale: false,
    brand: "Razer",
    model: "Razer Blade 15",
    release_year: 2021,
    processor: "Intel Core i7-11800H",
    ram: "32GB",
    storage: "1TB SSD",
    display_size: "15.6 inches",
    resolution: "1920 x 1080",
    graphics_card: "NVIDIA GeForce RTX 3080",
    weight: "4.4 lbs",
    price: 2599.99,
    colors: ["Black"],
    description:
      "The Razer Blade 15 is a high-performance gaming laptop with a sleek design and RGB keyboard.",
    ratings: {
      average: 4.7,
      count: 85,
    },
    reviews: [
      {
        username: "SophiaTaylor",
        rating: 5,
        comment: "Excellent for gaming and content creation.",
      },
      {
        username: "JamesBrown",
        rating: 4,
        comment: "Impressive build quality.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5014x5014?laptop-product",
    isOnFlashSale: false,
    brand: "Dell",
    model: "Dell Inspiron 14",
    release_year: 2021,
    processor: "Intel Core i5-1135G7",
    ram: "8GB",
    storage: "256GB SSD",
    display_size: "14 inches",
    resolution: "1920 x 1080",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "3.39 lbs",
    price: 749.99,
    colors: ["Platinum Silver"],
    description:
      "The Dell Inspiron 14 is a budget-friendly laptop with a compact design and decent performance.",
    ratings: {
      average: 4.2,
      count: 75,
    },
    reviews: [
      {
        username: "EmmaSmith",
        rating: 4,
        comment: "Good value for everyday use.",
      },
      {
        username: "NoahJohnson",
        rating: 3,
        comment: "Average performance.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5015x5015?laptop-product",
    isOnFlashSale: false,
    brand: "HP",
    model: "HP Omen 15",
    release_year: 2021,
    processor: "AMD Ryzen 9 5900HX",
    ram: "32GB",
    storage: "1TB SSD",
    display_size: "15.6 inches",
    resolution: "1920 x 1080",
    graphics_card: "NVIDIA GeForce RTX 3070",
    weight: "5.43 lbs",
    price: 1799.99,
    colors: ["Shadow Black"],
    description:
      "The HP Omen 15 is a gaming laptop with powerful AMD Ryzen and NVIDIA RTX performance.",
    ratings: {
      average: 4.5,
      count: 90,
    },
    reviews: [
      {
        username: "EthanBrown",
        rating: 5,
        comment: "Amazing gaming performance.",
      },
      {
        username: "AvaDavis",
        rating: 4,
        comment: "Heavy but worth it for gaming.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5016x5016?laptop-product",
    isOnFlashSale: false,
    brand: "ASUS",
    model: "ASUS VivoBook 15",
    release_year: 2021,
    processor: "AMD Ryzen 5 5500U",
    ram: "8GB",
    storage: "512GB SSD",
    display_size: "15.6 inches",
    resolution: "1920 x 1080",
    graphics_card: "AMD Radeon Graphics",
    weight: "3.75 lbs",
    price: 799.99,
    colors: ["Slate Grey"],
    description:
      "The ASUS VivoBook 15 is a budget-friendly laptop with a large display and solid performance.",
    ratings: {
      average: 4.3,
      count: 65,
    },
    reviews: [
      {
        username: "SophiaWilson",
        rating: 4,
        comment: "Good laptop for the price.",
      },
      {
        username: "JamesSmith",
        rating: 3,
        comment: "Decent performance, but not exceptional.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5017x5017?laptop-product",
    isOnFlashSale: false,
    brand: "Microsoft",
    model: "Surface Laptop Go",
    release_year: 2020,
    processor: "Intel Core i5-1035G1",
    ram: "8GB",
    storage: "128GB SSD",
    display_size: "12.4 inches",
    resolution: "1536 x 1024",
    graphics_card: "Intel UHD Graphics",
    weight: "2.45 lbs",
    price: 699.99,
    colors: ["Ice Blue"],
    description:
      "The Microsoft Surface Laptop Go is a compact and lightweight laptop for everyday tasks.",
    ratings: {
      average: 4,
      count: 50,
    },
    reviews: [
      {
        username: "LiamBrown",
        rating: 4,
        comment: "Great for students.",
      },
      {
        username: "OliviaJohnson",
        rating: 3,
        comment: "Not suitable for heavy tasks.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5018x5018?laptop-product",
    isOnFlashSale: false,
    brand: "Lenovo",
    model: "Lenovo ThinkPad X1 Carbon",
    release_year: 2021,
    processor: "Intel Core i7-1165G7",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "14 inches",
    resolution: "2560 x 1440",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.49 lbs",
    price: 1599.99,
    colors: ["Black"],
    description:
      "The Lenovo ThinkPad X1 Carbon is a business laptop with a lightweight design and excellent keyboard.",
    ratings: {
      average: 4.9,
      count: 80,
    },
    reviews: [
      {
        username: "EmmaDavis",
        rating: 5,
        comment: "Perfect for work.",
      },
      {
        username: "NoahSmith",
        rating: 5,
        comment: "Premium build quality.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5019x5019?laptop-product",
    isOnFlashSale: false,
    brand: "Acer",
    model: "Acer Chromebook Spin 13",
    release_year: 2020,
    processor: "Intel Core i5-10210U",
    ram: "8GB",
    storage: "128GB eMMC",
    display_size: "13.5 inches",
    resolution: "2256 x 1504",
    graphics_card: "Intel UHD Graphics 620",
    weight: "3.53 lbs",
    price: 799.99,
    colors: ["Steel Gray"],
    description:
      "The Acer Chromebook Spin 13 is a 2-in-1 Chromebook with a high-resolution display and long battery life.",
    ratings: {
      average: 4.2,
      count: 60,
    },
    reviews: [
      {
        username: "LiamWilson",
        rating: 4,
        comment: "Good Chromebook for productivity.",
      },
      {
        username: "OliviaSmith",
        rating: 3,
        comment: "Limited by Chrome OS.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5020x5020?laptop-product",
    isOnFlashSale: false,
    brand: "Dell",
    model: "Dell XPS 13",
    release_year: 2021,
    processor: "Intel Core i7-1165G7",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "13.4 inches",
    resolution: "3840 x 2400",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.8 lbs",
    price: 1799.99,
    colors: ["Platinum Silver"],
    description:
      "The Dell XPS 13 is a premium ultrabook with a stunning 4K display and exceptional build quality.",
    ratings: {
      average: 4.7,
      count: 95,
    },
    reviews: [
      {
        username: "SophiaJohnson",
        rating: 5,
        comment: "Gorgeous display and performance.",
      },
      {
        username: "JamesDavis",
        rating: 4,
        comment: "Solid choice for professionals.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5021x5021?laptop-product",
    isOnFlashSale: false,
    brand: "MSI",
    model: "MSI GS66 Stealth",
    release_year: 2021,
    processor: "Intel Core i9-11980HK",
    ram: "32GB",
    storage: "1TB SSD",
    display_size: "15.6 inches",
    resolution: "2560 x 1440",
    graphics_card: "NVIDIA GeForce RTX 3080",
    weight: "4.63 lbs",
    price: 2499.99,
    colors: ["Core Black"],
    description:
      "The MSI GS66 Stealth is a high-performance gaming laptop with a sleek and stealthy design.",
    ratings: {
      average: 4.8,
      count: 110,
    },
    reviews: [
      {
        username: "EthanSmith",
        rating: 5,
        comment: "Top-tier gaming laptop.",
      },
      {
        username: "AvaJohnson",
        rating: 4,
        comment: "Runs demanding games smoothly.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5022x5022?laptop-product",
    isOnFlashSale: false,
    brand: "HP",
    model: "HP Spectre x360 13",
    release_year: 2021,
    processor: "Intel Core i7-1165G7",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "13.3 inches",
    resolution: "1920 x 1080",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.87 lbs",
    price: 1299.99,
    colors: ["Nightfall Black"],
    description:
      "The HP Spectre x360 13 is a premium 2-in-1 laptop with a sleek design and vibrant display.",
    ratings: {
      average: 4.6,
      count: 85,
    },
    reviews: [
      {
        username: "EmmaWilson",
        rating: 5,
        comment: "Impressive build quality.",
      },
      {
        username: "NoahSmith",
        rating: 4,
        comment: "Great for both work and entertainment.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5023x5023?laptop-product",
    isOnFlashSale: false,
    brand: "Dell",
    model: "Dell XPS 15",
    release_year: 2022,
    processor: "Intel Core i9-11900H",
    ram: "32GB",
    storage: "1TB SSD",
    display_size: "15.6 inches",
    resolution: "3840 x 2160",
    graphics_card: "NVIDIA GeForce RTX 3060",
    weight: "4.0 lbs",
    price: 1999.99,
    colors: ["Platinum Silver", "Frost White"],
    description:
      "The Dell XPS 15 is a premium laptop with a stunning 4K display and powerful performance.",
    ratings: {
      average: 4.9,
    },
    reviews: [
      {
        username: "EmmaSmith",
        rating: 5,
        comment: "Beautiful 4K display.",
      },
      {
        username: "NoahBrown",
        rating: 4,
        comment: "Excellent build quality.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5024x5024?laptop-product",
    isOnFlashSale: false,
    brand: "Lenovo",
    model: "Lenovo Yoga C740",
    release_year: 2020,
    processor: "Intel Core i7-10510U",
    ram: "12GB",
    storage: "256GB SSD",
    display_size: "14 inches",
    resolution: "1920 x 1080",
    graphics_card: "Intel UHD Graphics 620",
    weight: "3.09 lbs",
    price: 899.99,
    colors: ["Mica"],
    description:
      "The Lenovo Yoga C740 is a 2-in-1 laptop with a sleek design and excellent battery life.",
    ratings: {
      average: 4.3,
      count: 70,
    },
    reviews: [
      {
        username: "SophiaTaylor",
        rating: 4,
        comment: "Good balance between performance and portability.",
      },
      {
        username: "JamesBrown",
        rating: 3,
        comment: "Decent for everyday use.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5025x5025?laptop-product",
    isOnFlashSale: false,
    brand: "Acer",
    model: "Acer Aspire 5",
    release_year: 2021,
    processor: "AMD Ryzen 5 5500U",
    ram: "8GB",
    storage: "512GB SSD",
    display_size: "15.6 inches",
    resolution: "1920 x 1080",
    graphics_card: "AMD Radeon Graphics",
    weight: "4.19 lbs",
    price: 699.99,
    colors: ["Silver"],
    description:
      "The Acer Aspire 5 is an affordable laptop with solid performance and a full HD display.",
    ratings: {
      average: 4,
      count: 65,
    },
    reviews: [
      {
        username: "EthanDavis",
        rating: 4,
        comment: "Great value for the price.",
      },
      {
        username: "AvaWilson",
        rating: 3,
        comment: "Decent budget laptop.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5026x5026?laptop-product",
    isOnFlashSale: false,
    brand: "Microsoft",
    model: "Microsoft Surface Laptop 4",
    release_year: 2021,
    processor: "AMD Ryzen 7 4980U",
    ram: "16GB",
    storage: "256GB SSD",
    display_size: "13.5 inches",
    resolution: "2256 x 1504",
    graphics_card: "AMD Radeon Graphics",
    weight: "2.79 lbs",
    price: 1299.99,
    colors: ["Platinum"],
    description:
      "The Microsoft Surface Laptop 4 offers a premium Windows experience with excellent battery life.",
    ratings: {
      average: 4.5,
      count: 85,
    },
    reviews: [
      {
        username: "EmmaMiller",
        rating: 5,
        comment: "Sleek and powerful laptop.",
      },
      {
        username: "NoahWilson",
        rating: 4,
        comment: "Great for productivity.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5027x5027?laptop-product",
    isOnFlashSale: false,
    brand: "HP",
    model: "HP Spectre x360 13",
    release_year: 2022,
    processor: "Intel Core i7-1260U",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "13.3 inches",
    resolution: "1920 x 1080",
    graphics_card: "Intel Iris Xe Graphics",
    weight: "2.8 lbs",
    price: 1399.99,
    colors: ["Nightfall Black", "Poseidon Blue", "Natural Silver"],
    description:
      "The HP Spectre x360 13 is a versatile 2-in-1 laptop with a premium design and vibrant display.",
    ratings: {
      average: 4.8,
      count: 95,
    },
    reviews: [
      {
        username: "EthanJohnson",
        rating: 5,
        comment: "Amazing build quality and performance.",
      },
      {
        username: "SophiaLee",
        rating: 4,
        comment: "Compact and lightweight for on-the-go use.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5028x5028?laptop-product",
    isOnFlashSale: false,
    brand: "Lenovo",
    model: "Lenovo Legion 5",
    release_year: 2021,
    processor: "AMD Ryzen 7 5800H",
    ram: "16GB",
    storage: "1TB SSD",
    display_size: "15.6 inches",
    resolution: "1920 x 1080",
    graphics_card: "NVIDIA GeForce RTX 3060",
    weight: "5.41 lbs",
    price: 1299.99,
    colors: ["Phantom Blue"],
    description:
      "The Lenovo Legion 5 is a gaming laptop with powerful AMD Ryzen and NVIDIA RTX performance.",
    ratings: {
      average: 4.7,
      count: 90,
    },
    reviews: [
      {
        username: "SophiaBrown",
        rating: 5,
        comment: "Amazing gaming laptop.",
      },
      {
        username: "JamesWilson",
        rating: 4,
        comment: "Runs demanding games smoothly.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
  {
    image: "https://source.unsplash.com/featured/5029x5029?laptop-product",
    isOnFlashSale: false,
    brand: "Apple",
    model: "MacBook Pro 14-inch",
    release_year: 2021,
    processor: "Apple M1 Pro",
    ram: "16GB",
    storage: "512GB SSD",
    display_size: "14 inches",
    resolution: "3024 x 1964",
    graphics_card: "Apple M1 Pro GPU",
    weight: "3.5 lbs",
    price: 1999.99,
    colors: ["Space Gray"],
    description:
      "The MacBook Pro 14-inch with Apple's M1 Pro chip offers exceptional performance and a stunning display.",
    ratings: {
      average: 4.8,
      count: 110,
    },
    reviews: [
      {
        username: "EthanJohnson",
        rating: 5,
        comment: "Incredible speed and display quality.",
      },
      {
        username: "AvaMiller",
        rating: 4,
        comment: "Ideal for creative professionals.",
      },
    ],
    createdAt: "2024-03-23T06:22:42.023Z",
  },
];

export const brands = [
  {
    name: "Apple",
    logo: "/brands/apple.svg",
  },
  {
    name: "Microsoft",
    logo: "/brands/microsoft.svg",
  },
  {
    name: "ASUS",
    logo: "/brands/asus.svg",
  },
  {
    name: "HP",
    logo: "/brands/hp.svg",
  },
  {
    name: "Dell",
    logo: "/brands/dell.svg",
  },
  {
    name: "Lenovo",
    logo: "/brands/lenovo.svg",
  },
  {
    name: "LG",
    logo: "/brands/lg.svg",
  },
  {
    name: "Acer",
    logo: "/brands/acer.svg",
  },
  {
    name: "MSI",
    logo: "/brands/msi.svg",
  },
  {
    name: "Razer",
    logo: "/brands/razer.svg",
  },
] as const;
